=== prudhviraaz14/FIF_POC/FIF_API/CcmTestFramework/dtd/request.dtd
<!--
    DTD for the XML representation of a FIF Request
    
    File name : $Workfile:   request.dtd  $
    Header    : $Header:   F:/GRUPPEN/PROJEKTE/PVCS_FIF/archives/FIF/KBAFIFQueueClient/request.dtd-arc   1.1   Mar 03 2004 15:49:18   goethalo  $
    Revision  : $Revision:   1.1  $
    
    History:
    $Log:   F:/GRUPPEN/PROJEKTE/PVCS_FIF/archives/FIF/KBAFIFQueueClient/request.dtd-arc  $
 
    Rev 1.1   Mar 03 2004 15:49:18   goethalo
 SPN-FIF-000020483: Added PVCS header.
    
-->
   
<!ELEMENT action-name (#PCDATA)>
<!ELEMENT request (action-name, request-params)>
<!ELEMENT request-params (request-param-list|request-param)+>
<!ELEMENT request-param-list (request-param-list-item*)>
<!ATTLIST request-param-list
    name CDATA #REQUIRED
  >
<!ELEMENT request-param-list-item (request-param-list|request-param)+>
<!ELEMENT request-param (#PCDATA)>
<!ATTLIST request-param
    name CDATA #REQUIRED
  >

=== prudhviraaz14/FIF_POC/FIF_API/WOEFIFQueueClient/test/modifyContract.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE request SYSTEM "request.dtd">
<request>
  <action-name>modifyContract</action-name>
  <request-params>
    <request-param name="transactionID"><![CDATA[WOE_TEST_MC_1]]></request-param>
    <request-param name="contractNumber"><![CDATA[000000156263]]></request-param>
	<request-param name="customerNumber"><![CDATA[000000156263]]></request-param>
    <request-param name="desiredDate"><![CDATA[2005.12.01 00:00:00]]></request-param>
    <request-param name="changeTariff"><![CDATA[Y]]></request-param>	
    <request-param name="newPricingStructureCode"><![CDATA[I1010]]></request-param>
	<request-param name="changeMinimumDuration"><![CDATA[Y]]></request-param>
    <request-param name="newMinPeriodDurationValue"><![CDATA[12]]></request-param>
  </request-params>
</request>

=== prudhviraaz14/FIF_POC/FIF_API/WOEFIFQueueClient/test/bwChange.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE request SYSTEM "request.dtd">
<request>
  <action-name>changeDSLBandwidth</action-name>
  <request-params>
    <request-param name="transactionID"><![CDATA[WOE_TEST_BW_1]]></request-param>
    <request-param name="accessNumber"><![CDATA[49;2159;114477]]></request-param>
    <request-param name="contractNumber"><![CDATA[000000156263]]></request-param>
    <request-param name="customerNumber"><![CDATA[000000086639]]></request-param>
    <request-param name="desiredDate"><![CDATA[2005.12.01 00:00:00]]></request-param>
    <request-param name="newDSLBandwidth"><![CDATA[DSL 1000]]></request-param>
	<request-param name="oldDSLBandwidth"><![CDATA[DSL 1000]]></request-param>
    <request-param name="newUpstreamBandwidth"><![CDATA[Standard]]></request-param>
    <request-param name="oldUpstreamBandwidth"><![CDATA[256]]></request-param>
    <request-param name="OMTSOrderID"><![CDATA[ARC001010101]]></request-param>
	<request-param name="rollenBezeichnung"><![CDATA[RB]]></request-param>
  </request-params>
</request>
